/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyschool.view;

import easyschool.model.DAO.TurmaDAO;
import easyschool.model.Session;
import easyschool.model.Turma;
import java.awt.Frame;

/**
 *
 * @author aluno
 */
public class InfoTurmView extends javax.swing.JFrame {

    /**
     * Creates new form InfoTurmView
     */
    Frame frame = this;
    Turma turma;

    public InfoTurmView() {
        initComponents();
        turma = Session.getInstance().getTurma();
        if (turma.getLocal() != null) {
            localLabel.setText("Local: " + turma.getLocal());
        } else {
            localLabel.setText("Local: Esperando aprovação");
        }

        if (turma.getNome() != null) {
            nomeMateriaLabel.setText(turma.getNome() + "(" + turma.getMateria() + ")");

        } else {
            nomeMateriaLabel.setText("Esperando aprovação(" + turma.getMateria() + ")");
            totalAlunosLabel.setText("Total de alunos: Esperando aprovação ");
        }
        int quantidade = TurmaDAO.getInstance().buscarQuantidadeAlunosPorTurma(turma.getId());
        alunosMatriculadosLabel.setText("Alunos matriculados: " + quantidade);
        horarioLabel.setText("Horário: " + turma.getHorario());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        alunosMatriculadosLabel = new javax.swing.JLabel();
        totalAlunosLabel = new javax.swing.JLabel();
        nomeMateriaLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        localLabel.setText("Local: Predio 3, Sala 5");

        horarioLabel.setText("Horário: Terça, 15h 30m; Quinta, 10h ");

        alunosMatriculadosLabel.setText("Alunos matriculados: 0");

        totalAlunosLabel.setText("Total de alunos que a sala suporta: 50");

        nomeMateriaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeMateriaLabel.setText("Calculo III");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(nomeMateriaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horarioLabel)
                            .addComponent(localLabel)
                            .addComponent(alunosMatriculadosLabel)
                            .addComponent(totalAlunosLabel))))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(nomeMateriaLabel)
                .addGap(18, 18, 18)
                .addComponent(localLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(horarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alunosMatriculadosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalAlunosLabel)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Session.getInstance().setTurma(null);
        HomePageProfessorView homeView = new HomePageProfessorView();
        homeView.setVisible(true);
        frame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoTurmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoTurmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoTurmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoTurmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoTurmView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alunosMatriculadosLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel localLabel;
    private javax.swing.JLabel nomeMateriaLabel;
    private javax.swing.JLabel totalAlunosLabel;
    // End of variables declaration//GEN-END:variables
}
