/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyschool.view;

import easyschool.model.Aluno;
import easyschool.model.DAO.AlunoDAO;
import easyschool.model.DAO.TurmaDAO;
import easyschool.model.Session;
import easyschool.model.Turma;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class StudentTurmeView extends javax.swing.JFrame {

    public String materia = "";
    Aluno aluno;
    Frame frame = this;
    private DefaultTableModel defaultTableModel = new DefaultTableModel();
    private ArrayList<Turma> turmas;

    /**
     * Creates new form StudentTurmeView
     */
    public StudentTurmeView() {
        initComponents();
        aluno = Session.getInstance().getAluno();
        sairMenu.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                LoginView loginView = new LoginView();
                loginView.setVisible(true);
                frame.setVisible(false);
                Session.getInstance().apagarDados();
            }
        });
        voltarMenu.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                HomePageStudentView home = new HomePageStudentView();
                home.setVisible(true);
                frame.setVisible(false);
            }
        });
    }

    public void init() {
        System.out.println("Matéria: " + materia);
        criarTable();
        Turma turmaAtual = AlunoDAO.getInstance().alunoTemTurma(aluno, materia);
        if (turmaAtual != null) {
            turmaLabel.setText("Turma: " + turmaAtual.getNome());
            localLabel.setText("Local: " + turmaAtual.getLocal());
            horarioLabel.setText("Horário: " + turmaAtual.getHorario());
        }
    }

    private void criarTable() {
        turmas = TurmaDAO.getInstance().buscarTurmasPorMateria(materia);
        defaultTableModel.addColumn("Nome");
        defaultTableModel.addColumn("Local");
        defaultTableModel.addColumn("Horário");
        defaultTableModel.addColumn("Disponível");
        for (int i = 0; i < turmas.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                turmas.get(i).getNome(),
                turmas.get(i).getLocal(),
                turmas.get(i).getHorario(),
                verificaVagaDisponivel(turmas.get(i))
            });

        }

        jTable.setModel(defaultTableModel);
        jTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int col = jTable.getTableHeader().columnAtPoint(e.getPoint());
                int line = jTable.getSelectedRow();
                System.out.println("Clicou na coluna" + col + "e na linha" + line);

            }
        });
    }

    private String verificaVagaDisponivel(Turma turma) {
        int alunosMatriculados = TurmaDAO.getInstance().buscarQuantidadeAlunosPorTurma(turma.getId());
        if (alunosMatriculados >= turma.getNumeroAlunos()) {
            return "Lotado";
        }
        return "Disponivel";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        turmaLabel = new javax.swing.JLabel();
        localLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        voltarMenu = new javax.swing.JMenu();
        sairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(213, 213, 213));

        turmaLabel.setText("Turma:");

        localLabel.setText("Local:");

        horarioLabel.setText("Horário:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Turmas");

        jButton1.setText("Matricular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addComponent(horarioLabel)
                    .addComponent(localLabel)
                    .addComponent(turmaLabel))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turmaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(localLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(horarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Local", "Horário", "Disponível"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        voltarMenu.setText("Voltar");
        jMenuBar1.add(voltarMenu);

        sairMenu.setText("Sair");
        jMenuBar1.add(sairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int line = jTable.getSelectedRow();
        Turma turma = turmas.get(line);

        if (AlunoDAO.getInstance().adicionarTurma(aluno, turma)) {
            turmaLabel.setText("Turma: " + turma.getNome());
            localLabel.setText("Local: " + turma.getLocal());
            horarioLabel.setText("Horário: " + turma.getHorario());
            JOptionPane.showMessageDialog(null, "Matriculado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar turma e aluno");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentTurmeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentTurmeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentTurmeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentTurmeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentTurmeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel localLabel;
    private javax.swing.JMenu sairMenu;
    private javax.swing.JLabel turmaLabel;
    private javax.swing.JMenu voltarMenu;
    // End of variables declaration//GEN-END:variables
}
